# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 'none'


stages:
- stage: build
  jobs:
  - job: build 
    pool:
      vmImage: windows-latest

    steps: 
    
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      displayName: restore the app
      inputs:
        command: 'restore'
        projects: '**/WebApp.csproj'


    - task: DotNetCoreCLI@2
      displayName: build the app 
      inputs:
         command: 'build'
         projects: '**/WebApp.csproj'
         arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: do the test
      inputs:
         command: 'test'
         projects: '! **/*UnitTest*.csproj'
         arguments: '--configuration $(BuildConfiguration)'
         
                
    - task: DotNetCoreCLI@2
      displayName: publish the app
      inputs:
         command: 'publish'
         publishWebProjects: true
         arguments: '--configuration $(BuildConfiguration)'
         
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: deploy 
  displayName: deploy to the web app 
  dependsOn: build 
  jobs:
  - job: deploy
    pool:
      vmImage: windows-latest
    steps: 


    - task: DownloadBuildArtifacts@1
      inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'mo'
         downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MOGUIA(0140fa3e-3836-4df1-ad41-12987b3c3243)'
        appType: 'webApp'
        WebAppName: 'appservicemo15'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
 
    
        




