# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 'none'


stages:
- stage: build
  jobs:
  - job: build 
    pool:
      vmImage: windows-latest

    steps: 
    
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: DotNetCoreCLI@2
      displayName: restore the app
      inputs:
        command: 'restore'
        projects: '**/WebApp.csproj'


    - task: DotNetCoreCLI@2
      displayName: build the app 
      inputs:
         command: 'build'
         projects: '**/WebApp.csproj'
         arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: do the test
      inputs:
         command: 'test'
         projects: '! **/*UnitTest*.csproj'
         arguments: '--configuration $(BuildConfiguration)'
         
    - task: DotNetCoreCLI@2
      inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(BuildConfiguration)'
        
         
    
    - task: CopyFiles@2
      displayName: copy to the artifact
      inputs:
       targetFolder: $(Build.ArtifactStagingDirectory)
       
         
    - task: PublishBuildArtifacts@1
      displayName: put it in the artifact
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    
  - job: databse 
    pool:
     vmImage: 'windows-2019'
     demands: msbuild

    steps:   
    - task: MSBuild@1
      inputs:
        solution: WebApp.Database/WebApp.Database.sqlproj
        msbuildArguments: --configuration $(BuildConfiguration)

    - task: CopyFiles@2
      displayName: copy to databse to the artifact
      inputs:
       targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      displayName: publish the database artifact
      inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: 'dacpac'
          publishLocation: 'Container'

- stage: deploy 
  displayName: deploy to the web app 
  dependsOn: build 
  jobs:
  - job: deploy
    pool:
      vmImage: windows-latest
    steps: 


    - task: DownloadBuildArtifacts@1
      inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'
         
     
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MOGUIA(0140fa3e-3836-4df1-ad41-12987b3c3243)'
        appType: 'webApp'
        WebAppName: 'appservicemo15'
        packageForLinux: '$(System.ArtifactsDirectory)'
        
        
    - task: DownloadBuildArtifacts@1
      displayName:  download the dacpac 
      inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'dacpac'
            downloadPath: '$(System.ArtifactsDirectory)'
    
        




